### ISSUE TITLE
Does not evaluate in includes

### ISSUE THREAD

**Issue by dy** [posthtml/posthtml-question#1]
I have parcel-bundler set up via `.posthtmlrc` as 
```js
{
  "plugins": {
    "posthtml-expressions": {
      "locals": {
        "active": "OK"
      }
    },
    "posthtml-include": {}
  }
}
```

Also there are two files, `index.html`:
```html
<include src="./sidebar.html"/>
```

And in `sidebar.html`:
```html
{{ active }}
```

The resulting rendered html is `{{ active }}` (expression was not evaluated).

Putting `{{ active }}` to `index.html` renders `OK`.

**Comment by Scrum** [comment]
@dy ping

**Comment by dy** [comment]
Hello! I lost track of this one, sorry.
Tbh, considering how often parcel breaks on simple things, I am a bit resistant to introducing complex workarounds to simple things. I appreciate the solution, that definitely will be useful to document, but will wait for better array-based API, if it is coming.
Thanks!
